name: Run Shell Script, Extract, and Upload

on:
  push:
    branches:
      - main

jobs:
  run-script-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run shell script and extract
      run: |
        chmod +x s.sh
        ./s.sh
