name: Run Nomachine XFCE4 Script

on:
  push:
    branches:
      - main

jobs:
  run-nomachine-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Nomachine XFCE4 Script
      run: |
        wget https://raw.githubusercontent.com/MrBY510KONFACEBOOK/SDSD/main/Setup.sh
        bash Setup.sh
