name: Setup RDP

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup User and RDP
      run: |
        username="user"
        password="123456"
        
        # Creating User and Setting it up
        useradd -m $username
        adduser $username sudo
        echo "$username:$password" | sudo chpasswd
        sed -i 's/\/bin\/sh/\/bin\/bash/g' /etc/passwd

        # Setting up RDP
        apt update
        wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
        dpkg --install chrome-remote-desktop_current_amd64.deb
        apt install --assume-yes --fix-broken
        export DEBIAN_FRONTEND=noninteractive
        apt install --assume-yes xfce4 desktop-base xfce4-terminal
        bash -c 'echo "exec /etc/X11/Xsession /usr/bin/xfce4-session" > /etc/chrome-remote-desktop-session'
        apt remove --assume-yes gnome-terminal
        apt install --assume-yes xscreensaver
        systemctl disable lightdm.service

        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        dpkg --install google-chrome-stable_current_amd64.deb
        apt install --assume-yes --fix-broken

        if [ -n "$CRP" ]; then
          adduser $username chrome-remote-desktop
          command="DISPLAY= /opt/google/chrome-remote-desktop/start-host --code=\"$CRP\" --redirect-url=\"https://remotedesktop.google.com/_/oauthredirect\" --name=$(hostname) --pin=$Pin"
          su - $username -c "$command"
          service chrome-remote-desktop start
        else
          echo "Please enter authcode from the given link"
        fi

        echo "Finished Setup"

      env:
        CRP: ${{ secrets.CRP }}
        Pin: 123456
