name: Run b.sh with CRP

on:
  push:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up bash
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Run b.sh script with CRP
        run: |
          bash b.sh "$CRP"
        env:
          CRP: ${{ secrets.CRP }}
